import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs-extra";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// --- CONFIGURAÇÃO ---
// Altere este caminho para o caminho do seu cofre do Obsidian
const vaultPath = "D:\\OneDrive\\OBSIDIAN\\FSN Second Brain";
const pluginDir = ".obsidian/plugins/obsidian-speech-to-text";
// --------------------

const targetDir = path.join(vaultPath, pluginDir);
const prod = (process.argv[2] === "production");

const buildAndDeploy = async () => {
    try {
        // Build
        await esbuild.build({
            banner: {
                js: banner,
            },
            entryPoints: ["main.ts"],
            bundle: true,
            external: [
                "obsidian",
                "electron",
                ...builtins,
            ],
            format: "cjs",
            target: "es2018",
            logLevel: "info",
            sourcemap: prod ? false : "inline",
            treeShaking: true,
            outfile: "main.js",
        });

        // Deploy
        await fs.ensureDir(targetDir);
        await fs.copyFile("main.js", path.join(targetDir, "main.js"));
        await fs.copyFile("manifest.json", path.join(targetDir, "manifest.json"));
        console.log("Plugin copiado para:", targetDir);

    } catch (e) {
        console.error(e);
        process.exit(1);
    }
};

buildAndDeploy();
